//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Socio
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Cedula { get; set; }
        public string Foto { get; set; }
        public string Direccion { get; set; }
        public string Sexo { get; set; }
        public string Edad { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string TipoMembresia { get; set; }
        public string LugarTrabajo { get; set; }
        public string DireccionTrabajo { get; set; }
        public string TelefonoOficina { get; set; }
        public string EstadoMembresita { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaSalida { get; set; }
    }
}
